### ISSUE TITLE
SROS2 documentation and design documents

### ISSUE THREAD

**Issue by miguelvelezmj25** [ros2/sros2#111]
Are there any design documents or documentation files about SROS2? I am able to follow the tutorials, but I do not understand how is that what I am doing enables secure communication between topics. For example, the first part of the tutorial makes me set

> export ROS_SECURITY_ENABLE=true
> export ROS_SECURITY_STRATEGY=Enforce

However, what would happen if I set ```ROS_SECURITY_STRATEGY```, but I set ```ROS_SECURITY_STRATEGY=false```? What are the other option values of the latter environmental variable?

Another example. After completing the first part of the tutorial, it says 

> These nodes will be communicating using authentication and encryption!

What exactly enabled authentication between the nodes? What enabled message encryption? Is the topic encrypted? How can I enable only authentication and not encryption?

**Comment by jacobperron** [comment]
I'm not aware of anything other than the documentation in this repository.

@ruffsl Do you if there is anything else?

**Comment by miguelvelezmj25** [comment]
Is there a place that I am missing in the current documentation that would answer the above questions?

**Comment by ruffsl** [comment]
Creating design document might be helpful in coordinating security efforts for ROS2 in-general, though I'm not sure that would be the place for user level documentation like what SROS setting should be used.

`ROS_SECURITY_ENABLE` simply controls if DDS security is used or not (conditional upon the DDS vendor selected also supports it). I think `Enforce` is the only option for`ROS_SECURITY_STRATEGY` at present, with the idea that we could add more behavior strategy in the future such as `Audit` to regulate the stringency of the access control plugin for permission development rather than just deployment.

@jacobperron , is there an example of a core ros2 package adding documentation that we could mimic? I asked about this back during the announcement about the soft release of index.ros.org but didn't get a response: https://discourse.ros.org/t/ros-2-documentation-home-moving-to-index-ros-org-doc-ros2/6612/8

**Comment by jacobperron** [comment]
@ruffsl We don't have doc jobs setup for individual packages (including core packages), but we do have some general [ROS 2 documentation](dex.ros.org/doc/ros2/) maintained at https://github.com/ros2/ros2_documentation.
IMO, opening a PR to add one or more detailed tutorials about SROS would be nice. Currently, I see that security is listed under the [features](https://index.ros.org/doc/ros2/Features/), but just points to this repository rather than a tutorial like many of the other links.

**Comment by mikaelarguedas** [comment]
@miguelvelezmj25 

> Are there any design documents or documentation files about SROS2? 

Not at the moment, it would be a good thing to improve the documentation indeed, the tutorial is currently just a "first steps" demo rather than a detailed documentation

> However, what would happen if I set ROS_SECURITY_STRATEGY, but I set ROS_SECURITY_STRATEGY=false? What are the other option values of the latter environmental variable?

`ROS_SECURITY_ENABLE` takes `true`, any other string in that environment variable will result in `false`: https://github.com/ros2/rcl/blob/d947655a532e8f607d788c25dd22db2f43ee6935/rcl/src/rcl/node.c#L288
If it is true, ROS will try to retrieve the security artifacts on the file system and instanciate the security plugins, otherwise it will create a node without any security plugins.

if `ROS_SECURITY_STRATEGY` contains `Enforce` it will result in `RMW_SECURITY_ENFORCEMENT_ENFORCE` anything else will result in `RMW_SECURITY_ENFORCEMENT_PERMISSIVE`
https://github.com/ros2/rcl/blob/d947655a532e8f607d788c25dd22db2f43ee6935/rcl/src/rcl/node.c#L302-L303.

That environment variable is considered only if `ROS_SECURITY_ENABLE` is true.
If `Enforce` is selected. The node will require all the security artifact to be available and fail to be created otherwise. If the permissive mode is selected, the node will be created the "secure" way if all artifacts can be found, otherwise an "unsecure" node will be created.

> What exactly enabled authentication between the nodes? 

By using ROS_SECURITY_ENABLE = "true" you tell the rcl and then rmw to instantiate the DDS-Security plugins. It will use the information in the other environment variables to retrieve the artifacts and instantiate the plugins (both Authentication and Cryptography plugins).

> What enabled message encryption? How can I enable only authentication and not encryption?

IIRC topics are encrypted by default if security is used. That option should be made available to the user on a per-topic basis, but isn't exposed at the moment.

> Is the topic encrypted? 

Yes, a way to confirm it is to listen to the interface on wireshark and see that the RTPS packets are encrypted.

---
@jacobperron 

 > IMO, opening a PR to add one or more detailed tutorials about SROS would be nice. Currently, I see that security is listed under the features, but just points to this repository rather than a tutorial like many of the other links.

The tutorial of this repo is currently available in the [tutorials page](https://index.ros.org/doc/ros2/Tutorials/).
I believe what we need here is a place to store more detailed feature documentation rather than a "tutorial" per se.
Is your recommendation to store that additional documentation on https://github.com/ros2/ros2_documentation repo directly ?

**Comment by jacobperron** [comment]
> Is your recommendation to store that additional documentation on https://github.com/ros2/ros2_documentation repo directly ?

Detailed documentation could live there or in this repo (and referenced from ros2_documentation).
I don't have a strong preference, but it is nice to have documentation live close to the implementation so it's easier to update them together.

**Comment by ruffsl** [comment]
> but it is nice to have documentation live close to the implementation so it's easier to update them together.

:+1: 

> Detailed documentation could live there or in this repo (and referenced from ros2_documentation).

Is there any particular documentation tool that core package are using, like sphinxes, that we should adopt here? If the docs are located in this repo, is there a way they get hosted by the index (e.g index.ros.org/doc/sros2 ), or would we use a host like readthedocs.org as done with colcon (e.g. sros2.readthedocs.io )?

**Comment by dirk-thomas** [comment]
> Is there any particular documentation tool that core package are using, like sphinxes, that we should adopt here?

Sphinx is being used by most ROS 2 docs.

> If the docs are located in this repo, is there a way they get hosted by the index (e.g index.ros.org/doc/sros2 )

**Comment by dirk-thomas** [comment]
> Is there any particular documentation tool that core package are using, like sphinxes, that we should adopt here?

Sphinx is being used by most ROS 2 docs.

> If the docs are located in this repo, is there a way they get hosted by the index (e.g index.ros.org/doc/sros2 )

No, since there are no repository specific doc jobs atm. In the future that is going to likely be the case.

> would we use a host like readthedocs.org as done with colcon (e.g. sros2.readthedocs.io )?

In the long term I would recommend against that since hosting the docs in different places will make it more difficult to search for them (except using a search engine). In the short term it might be an alternative to adding them to the [ros2_documentation](https://github.com/ros2/ros2_documentation/) repo which is rendered as https://index.ros.org/doc/ros2/

**Comment by kyrofa** [comment]
We've proposed a [design doc](https://github.com/ros2/design/pull/243) that should answer a lot of questions.

**Comment by miguelvelezmj25** [comment]
@kyrofa Thank you very much for linking the design doc. That answered a lot of my questions. However, there are still a few questions that I have. For example, I see that the ROS 2 Authentication plugin uses PKI and, when creating a key, **key.pem** is the private key for the node instance. However, which file corresponds to the public key? I want to run 2 nodes in separate machines. I was thinking of creating keys for each node in each machine and sharing their public keys in a central place (i.e., a third machine) or copying the public keys to the other's keystore. Is this structure possible? The tutorials and demos that I have seen online for running nodes in separate machines either replicate the keystores in all machines, sharing private keys!, or they have the keys stored in a central place, again sharing private keys!

**Comment by ruffsl** [comment]
> However, which file corresponds to the public key?

`cert.pem` is the x509 certificate that pertains to the public key, and key pair fingerprint/signature.

> I was thinking of creating keys for each node in each machine and sharing their public keys in a central place (i.e., a third machine) or copying the public keys to the other's keystore.

That's not how x509 certificates are used. The separate machines need only agree on a common trusted certificate authority (CA). Instead of distributing the public certificates of each node, you should distribute/designate the public certificate of the trusted root CA used to sign all public cert for nodes.

I suggest further reading either the relevant sections in the Secure DDS spec from OMG, or how x509 certs and chains of trust are used in other similar security transports like TLS:
https://en.wikipedia.org/wiki/X.509

**Comment by jacobperron** [comment]
Since there are now design docs ([1](http://design.ros2.org/articles/ros2_access_control_policies.html) and [2](http://design.ros2.org/articles/ros2_dds_security.html)), I'm going to close this issue.

Feel free to continue discussion though.

**Comment by kyrofa** [comment]
> What encryption algorithm is being use when nodes communicate securely?

Please see the "cryptography" section of [the design doc](http://design.ros2.org/articles/ros2_dds_security.html) which gives you a high-level answer (Advanced Encryption Standard (AES) in Galois Counter Mode (AES-GCM)) and pointers to learn more.

> Where in the ROS source are message encrypted and decrypted?

It's within the DDS implementation, so it will be different depending on what you're using.

> Can the selection of algorithm be parameterized?

I don't believe so. See section 9.5 of the [DDS-Security spec](https://www.omg.org/spec/DDS-SECURITY/1.1/PDF) for more details.

**Comment by ruffsl** [comment]
The DDS Security plugin used is simply the default one, as specified by OMG. The spec established the interface for folks to author their own custom security plugins, but at the cost of interoperability.
