### ISSUE TITLE
Support for cyclonedds on ROS2 Humble

### ISSUE THREAD

**Issue by dsakshay** [ros2/sros2#291]
Is SROS2 supported for rmw_cyclonedds_cpp on ROS2 humble? I see that only fastrtps and connextdds are supported? 
In the readme it does SROS2 will be designed to work with any middleware, but would I able be able to run it on cyclonedds? 

Could you please let me know if there is support already for this implementation or is there a plan to do this in the future?

**Comment by clalancette** [comment]
Yes, it is supported with CycloneDDS.  You can follow the tutorials at http://docs.ros.org/en/humble/Tutorials/Advanced/Security/Security-Main.html .

That said, I'll leave this open because https://github.com/ros2/sros2/blob/rolling/README.md is indeed out-of-date.  If you'd like to submit a pull request updating that language, we'd be happy to review it.

**Comment by mikaelarguedas** [comment]
The fixup to the README is addressed as part of https://github.com/ros2/sros2/pull/295

Although I'm questioning the motivation for having the docs / tutorials duplicated between docs.ros.org and this repo, as it seems to increase maintenance burden and chances for them to be out of sync
