### ISSUE TITLE
Bionic: FastRTPS security tests fail

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/sros2#46]
On Bionic default openssl/libssl is 1.1.0:

## With Connext
no support for 1.1.0 so we need to install custom version of 1.0.2 provided by RTI

### Combinations tested:
  - ca generated with 1.0.2(used in the tests) and fastrtps using SSL 1.1.0 runtime libs: fail
  - ca generated with 1.1.0 and fastrtps using SSL 1.1.0 runtime libs: fail
  - manually remove openssl/libssl 1.1.0 and install libssl and openssl 1.0.2 and generate certificates by hand: WORKS

### Path forward
As I don't see forcing the use of openssl 1.0.2 as a viable path forward for bionic (as it conflicts with the system one and will force people to uninstall a ton of stuff), we need to figure out how to **tweak certificate and key generation in sros2** to allow that use case.
A lead to explore is that is looks that [our certificates are SSLv1](https://github.com/ros2/system_tests/blob/c4bf2a6af1929c35cb3c1e730eefb7c86bb35f05/test_security/test/test_security_files/publisher/cert.pem#L3) and fail, certs used in Fast-RTPS testing are [SSLv3](https://github.com/eProsima/Fast-RTPS/blob/ede928724f8f670d5c83acec0d5eddd45aa76e48/test/certs/mainsubcert.pem#L3) and pass.

related to ros2/ros2#481

**Comment by mikaelarguedas** [comment]
CI jobs [here](https://github.com/ros2/system_tests/pull/265#issue-185105464)

Associated PRs to review: https://github.com/ros2/sros2/pull/47 https://github.com/ros2/system_tests/pull/265

Context for review:

This extension is now necessary with OpenSSL 1.1.
The reason is that we need to dissociate the certificates from the (root) certificate authority and the certificates generated and signed by the CA and used by our nodes.
We do that by specifying `CA:true` for the certificate of the Certificate Authority and `CA:false` for the other certificates (that belong to entities that are NOT Certificate Authorities)

Ready for review

**Comment by ruffsl** [comment]
@mikaelarguedas , In addition to [`key_cert_sign`](https://github.com/ros/ros_comm/blob/5b1d1b3a34477ee31029189aa1ea49ed3c00df1b/tools/sros/conf/keyserver_config.yaml#L12-L16) you used resolve this issue here, do you suppose there are any other extensions we should be adding to our auto generated x.509 certificates, like [`path_length`](https://github.com/ros/ros_comm/blob/5b1d1b3a34477ee31029189aa1ea49ed3c00df1b/tools/sros/conf/keyserver_config.yaml#L7-L11) to limit the length of CA chain could extended, or more common extentions needed for other transport certficiates like [`digital_signature, key_encipherment, key_agreement`](https://github.com/ros/ros_comm/blob/5b1d1b3a34477ee31029189aa1ea49ed3c00df1b/tools/sros/conf/keyserver_config.yaml#L49-L54)

I don't think I ever read about any certificate extension requirements in the DDS security spec unlike the [IETF's TLS spec](https://tools.ietf.org/html/rfc5246), but perhaps OMG thought those would be self evident.

**Comment by mikaelarguedas** [comment]
Yeah I considered it but went for the minimal fix for now as this seems to match the extensions currently used but the DDS vendors we target. we can definitely consider other common extensions later on.

Regarding path length I didnt make assumptions on it, as currently it's always one but mostly because the certificate setup is still pretty primitive. But we could think of scenarios where this doesnt apply at which point it will mostly be putting an arbitrary number. Then enforcing a length of `1` for now wouldn't break anything.

> I don't think I ever read about any certificate extension requirements in the DDS security spec ...

Yeah I had the same feeling and figured I'll take a closer look at the spec to see if it was just assumed good practice. I don't recall the spec covering certificate extensions at all but I haven't read 1.1 yet so maybe this is now covered.

**Comment by ruffsl** [comment]
> Then enforcing a length of 1 for now wouldn't break anything.

To be conservative with the length, I think you'd want to set this is 0, 
As then no derived child CA could ever be created using the root CA.
However, the root CA is self signed, so this more like a safety rather than a restriction on the authority,
given the root CA could re-sign and change its self imposed extensions.
