### ISSUE TITLE
Unnecessary `/` before node name in  tutorial

### ISSUE THREAD

**Issue by left4taco** [ros2/sros2#92]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - Build from source
- Version or commit hash:
  - 0.6.2
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - Doesn't apply

#### Steps to reproduce issue
While following the steps in the tutorial, I failed to execute these commands:
```bash
$ ros2 security create_key demo_keys /talker
Namespace( command='security',  verb='create_key', NAME='/talker', ROOT='demo_keys', _command=<sros2.command.security.SecurityCommand object at 0x7f8c8d1395c0>, _verb=<sros2.verb.create_key.CreateKeyVerb object at 0x7f8c8ce26ef0>)
bad character in requested key name: /talker
```

It'll succeed if I changed the last parameter(key name, aka ROS node name) to `talker`. Looks like the `/` is unnecessary.

**Comment by ruffsl** [comment]
It looks like your reading documentation from the master branch while running the last release branch. Some changes have occurred since then, namly requirement for FQN path arguments.

https://github.com/ros2/sros2/compare/0.6.2...master

https://github.com/ros2/sros2/commit/e0f6831ac81c1cf9c31f550e019f725527a9e1e8

**Comment by left4taco** [comment]
@ruffsl Thanks. I see the changes. That'll work.
